/**
 * Don't hit me! Id is generated by the last filename, which are numbers.
 * Ugly, but saves time in db investigation xP
 */
const fs = require('fs');
const path = require('path');

module.exports = {
    generateId : function(entityName) {
        const folder = path.join(__dirname + '/out/' + entityName);

        return Math.max(
            fs.readdirSync(folder)
        ) + 1
    }
};